#!/usr/bin/env bash

# This is the default configuration.

hostname="arch"
username="username"
user_groups="wheel,audio,video,optical,storage"

language="fr_FR"
keymap="fr"
timezone="Europe/Paris"

dotfiles_url="https://github.com/nargacu83/dotfiles"
dotfiles_command="./install.sh"

# Enable multilib for 32 bits applications
multilib=1
# Number of pacman parallel downloads
parallel_downloads=0
# List of all of your mounted points
fstab=(
    "UUID -> /mount/path -> defaults -> ext4"
)
