#!/usr/bin/env bash


print_message "Creating user..."


function change_password() {
  passed=1
  while [[ ${passed} != 0 ]]; do
    passwd ${1}
    passed=$?
  done
  exit 0
}

print_inner_message "Setting root password"

chroot_cmd change_password root

print_inner_message "Adding ${username}..."

chroot_cmd useradd -m ${username}

print_inner_message "Setting ${username} password..."

chroot_cmd change_password ${username}

print_inner_message "Adding groups to ${username}"

chroot_cmd usermod -aG ${user_groups} ${username}

