#!/usr/bin/env bash


print_message "Creating user..."


function root_password() {
  passed=1
  while [[ ${passed} != 0 ]]; do
    passwd root
    passed=$?
  done
  exit 0
}

function user_password() {
  passed=1
  while [[ ${passed} != 0 ]]; do
    passwd ${username}
    passed=$?
  done
  exit 0
}

print_inner_message "Setting root password"

chroot_function "root_password"

print_inner_message "Adding ${username}..."

chroot_cmd "useradd -m ${username}"

print_inner_message "Setting ${username} password..."

chroot_cmd user_password

print_inner_message "Adding groups to ${username}"

chroot_cmd usermod -aG ${user_groups} ${username}

