#!/usr/bin/env bash

function pacman_install() {
    chroot_sudo_cmd /mnt sudo -u ${USER} pacman -S --needed --noconfirm ${1} || print_message "Could not install package: ${1}"
}

function aur_install() {
    chroot_sudo_cmd paru -S --noconfirm --noprovides --skipreview ${1} || print_message "Could not install aur package: ${1}"
}

function flatpak_install() {
    chroot_user_cmd /mnt flatpak install -y ${1} || print_error "Could not install flatpak: ${1}"
}

print_message "Updating keyring..."
# Install archlinux keyring to avoid PGP Signature errors
pacman_install archlinux-keyring
# Update for the keyring
arch-chroot /mnt sudo -u ${USER} pacman -Syu --noconfirm || print_message "Unable to update the system"

print_message "Installing pacman packages..."
for package in "${PACKAGES[@]}"; do
    pacman_install $package || print_message "Could not install package: $package"
done

if [ ${INSTALL_AUR} -eq 1 ]; then
    print_inner_message "Installing AUR packages..."
    for package in "${AUR[@]}"; do
        aur_install $package || print_error "Could not install AUR package: $package"
    done
fi

if [ ${INSTALL_FLATPAKS} -eq 1 ]; then
    print_inner_message "Installing Flatpaks..."
    for flatpak in "${FLATPAKS[@]}"; do
        flatpak_install $flatpak || print_error "Could not install flatpak: $flatpak"
    done
fi
