#!/usr/bin/env bash

print_inner_message "Setting parallel downloads..."
 
if [ ${parallel_downloads} -gt 0 ]; then
  sed -i '/^#\ParallelDownloads =/{N;s/#//g}' /etc/pacman.conf
fi

print_inner_message "Setting the system clock..."

timedatectl set-ntp true
timedatectl set-timezone ${time_zone}

print_message "Installing base..."

pacstrap /mnt base linux linux-firmware

# CHROOT

print_inner_message "Creating symlink for the localetime"

ln -sf /usr/share/zoneinfo/${time_zone} /etc/localtime

print_inner_message "Setting the hardware clock"

chroot_cmd hwclock --systohc

print_inner_message "Setting system language"

chroot_enter
echo "LANG=\"${language}.UTF-8\"" >> /etc/locale.conf
echo "${language}.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "KEYMAP=${keymap}" > /etc/vconsole.conf
chroot_exit

print_inner_message "Setting hosts"

chroot_enter
echo ${hostname} > /etc/hostname
echo "127.0.1.1 ${hostname}.localdomain ${hostname}" >> /etc/hosts
exit 0
chroot_exit

chroot_enter
pacman -S --needed --noconfirm networkmanager git
systemctl enable NetworkManager
chroot_exit
