#!/usr/bin/env bash

print_inner_message "Setting installation parallel downloads..."
 
if [ ${parallel_downloads} -gt 0 ]; then
  sed -i '/^#\ParallelDownloads =/{N;s/#//g}' /etc/pacman.conf
fi

print_inner_message "Setting the system clock..."

timedatectl set-ntp true
timedatectl set-timezone ${timezone}

print_message "Installing base..."

pacstrap /mnt base linux linux-firmware

print_inner_message "Generating FSTAB..."
genfstab -U -p /mnt >> /mnt/etc/fstab
